import icon1 from "../assets/imp.png";

export const impactArticlesList = [
  {
    id: 1,
    img: icon1,
    title: "Establishment of support infrastructures",
    text: "Eco & Partner Consult Limited is a registered consulting firm with over 20 years’ experience providing Environmental, Social Assessment, Agro-processing and Management solutions in Uganda and the region.Over the past years, we have pursued a policy of delivering professional service while maintaining an understanding of the client’s needs, particularly the need to achieve both operational and environmental management objectives within limited timelines.",
    bigText:
      "In the four new hubs, NOPP will construct and maintain roads critical for oil palm development, production and marketing. Some 300 km of access roads and 910 km of farm roads will be constructed. In Kalangala, there remain about180 km of roads yet to be constructed. If they are not completed under VODP2, then Government will finance these roads as part of its contribution to NOPP. All roads will be delineated with farmers and, to the extent possible, constructed before the oil palm is planted, so as to ensure that farmers do not plant in the areas earmarked for roads, and facilitate the transport of seedlings and fertilizers. Road construction will be contracted out, while supervision of construction will be done by the PMU with the assistance of the District Local Governments. Road maintenance will be funded by the Project prior to the start of the oil palm harvesting phase, after which the farmers, and for certain roads the Districts, will be fully responsible for maintenance. NOPP will also finance the provision of fertilizer storage capacity of 15,000 tons in each hub. New ferries and landing sites for Buvuma and Kalangala will be funded under the IFAD loan for VODP2, though if it is not possible to make these expenditures prior to the completion of VODP2, then Government will finance them as per the NOPP budget.",
  },
  {
    id: 2,
    img: icon1,
    title: " Sustainability of the programme results",
    text: "Eco & Partner Consult Limited is a registered consulting firm with over 20 years’ experience providing Environmental, Social Assessment, Agro-processing and Management solutions in Uganda and the region.Over the past years, we have pursued a policy of delivering professional service while maintaining an understanding of the client’s needs, particularly the need to achieve both operational and environmental management objectives within limited timelines.",
    bigText:
      "Sustainability of the programme results is built into the character of the commercial partnership between the private sector company and smallholder producers. The private sector partner(s) has a vested interest not only in ensuring that smallholder production is sustained to achieve full utilisation of milling capacity, but also that it is profitable for those smallholder growers. For smallholder oil palm growers, the private sector partner offers them a secured and reliable market for their production, and a regular monthly income; and it is thus fully in their interests to continue producing oil palm and selling it to the CPO mill. In this context, the role of Government will be to facilitate the maintenance of existing commercial relationships between producers and private sector partners, and to stimulate the further growth of the oil palm sector, in a way that is inclusive and sustainable. This it will achieve through an enabling policy and institutional framework that encourages responsible investment at all levels; and by providing the sector with public goods and services to reduce the transaction costs to investors.",
  },
  {
    id: 3,
    img: icon1,
    title: "Household Mentoring",
    text: "Eco & Partner Consult Limited is a registered consulting firm with over 20 years’ experience providing Environmental, Social Assessment, Agro-processing and Management solutions in Uganda and the region.Over the past years, we have pursued a policy of delivering professional service while maintaining an understanding of the client’s needs, particularly the need to achieve both operational and environmental management objectives within limited timelines.",
    bigText:
      "Household Mentoring which is used to enable household members to jointly self-assess the challenges they face and identify the actions they would like to take. In particular, it is expected to help them address issues around HIV/AIDS and nutrition; improve the distribution of household tasks; better manage higher and regular incomes and make decisions more equitably on their use; improve household relations, wellbeing and self-confidence; and ultimately increase household incomes. The involvement of parents and their sons and daughters in the process will also help to create economic opportunities for youth. The activities will target 8,070 selected households. Households that “graduate” from the Household Mentoring programme after 12 to 24 months will be encouraged to assist others in their communities. To leverage its impact, the intervention will also target community leaders, and will work with oil palm growing households at the unit level where collaboration can generate benefits for all members. NOPP will also support complementary, district level efforts in the areas of HIV/AIDS, gender equality and nutrition efforts, with locally prioritised activities; and it will promote sports and cultural activities, as identified by community members, to in still healthy lifestyles among the youth, offer female youth an opportunity to participate in these types of activities, and create an entry point for discussing and identifying livelihood opportunities for rural youth.",
  },
  {
    id: 4,
    img: icon1,
    title: "Improved land access and tenure security",
    text: "Eco & Partner Consult Limited is a registered consulting firm with over 20 years’ experience providing Environmental, Social Assessment, Agro-processing and Management solutions in Uganda and the region.Over the past years, we have pursued a policy of delivering professional service while maintaining an understanding of the client’s needs, particularly the need to achieve both operational and environmental management objectives within limited timelines.",
    bigText:
      "Improved land access and tenure security, NOPP has promoted three sets of activities. First, participatory land use planning has be used to identify and accommodate different land uses in the oil palm growing communities around the CPO mills, taking into consideration the rights of owners and users to decide on the use of their lands but also recognizing that their use can impact on the livelihoods of others. Second, while no major land acquisition will be supported under NOPP, information will continue to be collected on the post-payment livelihood decisions made by the compensated households in Buvuma; training will be provided on procedures for land acquisition and compensation; and technical assistance will strengthen the PMU’s capacity in this area. Third, NOPP will support land tenure security measures, including civic education and public sensitization for communities involved in or affected by oil palm growing; local land dispute resolution and legal advice; and support for land registration. The activities will be implemented through “Land Information and Resource Centres” –para-legal advice centres that will be established and supported for five years; after which, if considered sufficiently useful, they may be taken up by the District government.",
  },
  {
    id: 5,
    img: icon1,
    title: "Alternative economic opportunities",
    text: "Eco & Partner Consult Limited is a registered consulting firm with over 20 years’ experience providing Environmental, Social Assessment, Agro-processing and Management solutions in Uganda and the region.Over the past years, we have pursued a policy of delivering professional service while maintaining an understanding of the client’s needs, particularly the need to achieve both operational and environmental management objectives within limited timelines.",
    bigText:
      "The sub-component is targeted primarily at those households within the oil palm growing communities that do not directly benefit from the oil palm investment: an estimated 75% of these households will participate in at least one of the activities offered. However, the activities will also be open to oil palm growers too, and an estimated 40% of them (23,700 households) will participate. Activities will specifically target women, youth and poorer households, using gender and age sensitive approaches. Support will be provided to enable non-OP and OP growers to enhance the productivity, sustainability and diversification of their crop and livestock enterprises; apply tailored climate-smart agriculture practices that not only support yield but also food and nutrition security; strengthen their linkages to local markets for their produce; and ultimately increase the profitability of their enterprises as well as improve resilience and reduce risks to livelihoods through sustainability and diversification. Activities will include: (a) improving extension service delivery, by training the extension workers and improving their, and farmers’, access to ICT- based agriculture information; (b) establishing farmer-led trial plots to enhance farmers’ agricultural skill development, using Farmer Field Schools; and (c) improving farmer access to quality agricultural inputs for field/horticultural crops and small livestock production. The Project will also provide support to households to identify, develop and finance micro and small rural enterprises, with target participation rates of 50% for both women and youth. The activities will include: (a) the establishment of business incubation services: scoping and validating business opportunities, prototyping of business opportunities, trainings in business skills development, and mentorship sessions; and (b) improved access to financial services: promotion of Village Savings and Loans Association. (VSLA), and reducing rural financial institutions’ risks to lend to the target group.",
  },
  {
    id: 6,
    img: icon1,
    title: "Scaling-up smallholder oil palm development",
    text: "Eco & Partner Consult Limited is a registered consulting firm with over 20 years’ experience providing Environmental, Social Assessment, Agro-processing and Management solutions in Uganda and the region.Over the past years, we have pursued a policy of delivering professional service while maintaining an understanding of the client’s needs, particularly the need to achieve both operational and environmental management objectives within limited timelines.",
    bigText:
      "NOPP will establish sustainable commercial partnerships between smallholder oil palm growers and private processors. In total, it will involve some 11,000 growers with a 19,700 ha under oil palm, in four new hubs where the crop will be planted for the first time, and in Kalangala where production is already established.",
  },
  {
    id: 7,
    img: icon1,
    title: "Private sector-led infrastructure development",
    text: "On Buvuma Island, Bidco will establish a nucleus estate for oil palm production of approximately 5,000 ha, plus the estate road network. In all the new hubs, the private sector partner will also finance the establishment of a nursery, to supply the smallholder growers with oil palm seedlings; as well as a CPO mill to process the FFBs supplied by the growers ...",
    bigText:
      "On Buvuma Island, Bidco will establish a nucleus estate for oil palm production of approximately 5,000 ha, plus the estate road network. In all the new hubs, the private sector partner will also finance the establishment of a nursery, to supply the smallholder growers with oil palm seedlings; as well as a CPO mill to process the FFBs supplied by the growers. The mill will be established once 3,000 ha of smallholder oil palm have been planted; the capacity can expand as the area under cultivation further increases.",
  },
  {
    id: 8,
    img: icon1,
    title: "Development of OPG organizations",
    text: "Technical support services (TSS) for oil palm plantation establishment in the new hubs have been provided initially through the hub start-up team. However, following establishment of the plantations, the start-up team will hand over to a dedicated TSS team, who will provide the oil palm growers with the necessary production services ...",
    bigText:
      "Technical support services (TSS) for oil palm plantation establishment in the new hubs have been provided initially through the hub start-up team. However, following establishment of the plantations, the start-up team will hand over to a dedicated TSS team, who will provide the oil palm growers with the necessary production services. The idea will be to keep the TSS light in terms of team members and outsource service provision to the extent possible; and from the start, mechanisms will be put in place for the eventual full cost recovery for the services delivered to the growers. Robust administrative and IT systems will be established to facilitate this process and ensure timely payments for their FFBs. In Kalangala, where KOPGT has provided technical services to the oil palm growers, the challenge is to assist it to limit its service delivery costs – a process that has already started. The move from KOPGT to a Kalangala Hub TSS entity will be informed by a review of KOPGT, to be conducted prior to NOPP start-up, and the drawing up of an action plan for KOPGT’s institutional transformation.",
  },
];
