import icon1 from "../assets/imp.png";

export const projectHubList = [
  {
    id: 1,
    img: icon1,
    title: "Mayuge",
    text: "Mayuge hub comprises of the districts of Mayuge, Bugiri and Namayingo. Previously, the project had registered 3,435 potential farmers (F=21%) who pledged 5,280 ha for the establishment of oil palm. In Mayuge hub, 1,793.99 ha is now re-surveyed, for 4-point coordinates, for 2,225 farmers. From the 1,792.99ha smallholders’ land surveyed. The farmers in Buwaaya and Mpungwe Sub Counties have so far prepared 116 ha to for planting oil palm on-going activities include: Lining/pegging, and holing in preparation for planting.",
    bigText: [
      "Mayuge hub comprises of the districts of Mayuge, Bugiri and Namayingo. Previously, the project had registered 3,435 potential farmers (F=21%) who pledged 5,280 ha for the establishment of oil palm. In Mayuge hub, 1,793.99 ha is now re-surveyed, for 4-point coordinates, for 2,225 farmers. From the 1,792.99ha smallholders’ land surveyed. The farmers in Buwaaya and Mpungwe Sub Counties have so far prepared 116 ha to for planting oil palm on-going activities include: Lining/pegging, and holing in preparation for planting.",
      "In addition, BIDICO /OPBL Agro-industries have expanded their operations to plant 5,000 hectares of oil palm under smallholder outgrowers in Mayuge bringing the total to 12,500ha (5,000ha nucleus + 2,500ha in Buvuma and 5.000ha in Mayuge). So far 78 farmers have prepared (lined and holed) 55.4 hectares (8,866 holes) to start planting oil palm starting in March 2024 first rains season in Buwaaya and Mpungwe Sub Counties.",
      "In terms of institutional development, each District will have a primary Cooperative and a secondary Co-operative/Union will be formed in the later stages, at the hub level. The primary co-operatives in each district will provide both financial and material services to the oil palm farmers. In Namayingo and Bugiri District, mobilisation of surveyed farmers for the formation of primary cooperatives was conducted. An interim leadership committee was elected in each district with representatives from all the sub-counties with suitable land for oil palm production.",
      "In the reporting period, the progress made includes single-sourcing the service provider, with process at the Solicitor General stage for contract approval – the contract signing is expected in February 2024, upon which the attendant Withdrawal Application shall be submitted. Listing of potential beneficiaries is proceeding and thus far; Mayuge (1,017 farmers with 776 Ha), Bugiri (405 farmers with 323 Ha) and Namayingo (199 farmers with 185 Ha). The baselines were to be established by mid-February 2024. For effective management of the grant, an implementation plan was drawn up and task forces within the implementing DLGs proposed – Mayuge, Namayingo and Bugiri DLG have already instituted their team.",
    ],
  },
  {
    id: 2,
    img: icon1,
    title: "Masaka",
    text: "Masaka hub comprises of the districts of Masaka, Kalungu and Kyotera. In the year of reporting, entry meetings were conducted in Kalungu and Kyotera, where the MoU for cooperation between MAAIF/NOPP and the DLGs was introduced and submitted for consideration by the leadership. In Masaka hub, an additional 566 ha has been identified, bringing the total up to 1,200 ha, and potential OPGs up from 404 to 600.",
    bigText: [
      "Masaka hub comprises of the districts of Masaka, Kalungu and Kyotera. In the year of reporting, entry meetings were conducted in Kalungu and Kyotera, where the MoU for cooperation between MAAIF/NOPP and the DLGs was introduced and submitted for consideration by the leadership. In Masaka hub, an additional 566 ha has been identified, bringing the total up to 1,200 ha, and potential OPGs up from 404 to 600.",
      "In the previous reporting periods, an entry meeting was held to explain the implementation modalities to district stakeholders. A Memorandum of Understanding was subsequently signed between MAAIF/NOPP and Masaka District Local Government. An experiential learning visit was conducted to Kalangala district, for the Local Leadership of Masaka and Kyotera districts - there were 64 participants (27% women).",
      "In Kyotera district, the Ministry of Lands, Housing and Urban Development together with MAAIF and the District Local Government have completed the identification and valuation of project affected persons (PAPs) on the Sango Bay land. To date, government has handed over 16,745 hectares of Sango Bay land to BIDCO and its partners for nucleus establishment in the sub-counties of Kasasa, Kakuuto, Kabira, Mutukula TC and Kyebe.",
    ],
  },
  {
    id: 3,
    img: icon1,
    title: "Bavuma",
    text: "The project, in partnership with the Buvuma District Local Government leadership, has conducted sensitization and mobilization meetings across the main island. These have been all-inclusive, with stakeholders invited to both formal and informal sittings to clarify roles and responsibilities, manage expectations, present progress on the pledging of farmland for oil palm growing as well as respond to any emerging issues. To date, over 2,550 farmers have been mobilized and sensitized on their roles and responsibilities including understanding the benefits of oil palm growing.",
    bigText: [
      "The project, in partnership with the Buvuma District Local Government leadership, has conducted sensitization and mobilization meetings across the main island. These have been all-inclusive, with stakeholders invited to both formal and informal sittings to clarify roles and responsibilities, manage expectations, present progress on the pledging of farmland for oil palm growing as well as respond to any emerging issues. To date, over 2,550 farmers have been mobilized and sensitized on their roles and responsibilities including understanding the benefits of oil palm growing.",
      "The tripartite Memorandum of Understanding (MoU) between MAAIF, NOPP and OPBL, for the establishment of smallholder oil palm plantations in Buvuma, was signed on June 20, 2022. The purpose of the MoU is to streamline contractual arrangements between OPBL and MAAIF/NOPP. A Contract Management Team was constituted, with the responsibility of contract oversight, including quality assurance and harmonization of prices of inputs and services supplied to the farmers, and in the future, the cost of Fresh Fruit Bunches (FFBs).",
      "The first phase of out-growers land was surveyed and mapped in 2021-22 for 323 farmers totalled 634.21 hectares in the four sub-counties of Buvuma Town Council, Nairambi, Busamuzi and BuwooyaThe second survey covered 171 farmers covering 366 hectares. In FY 2022-2023, a total of 1072.69 ha of land belonging to 631 smallholder farmers has been surveyed and mapped in Buvuma.",
      "The Hub has a target of 2,500 ha of oil palm for smallholders, and for the FY of reporting, 349.36 ha were planted against the planned 500, bringing the total oil palm establishment to 1,304.18 ha. An additional 385 ha have been identified and surveying is ongoing. Table 1 below articulates the progress in the establishment of out-growers hectarage.",
    ],
  },
  {
    id: 4,
    img: icon1,
    title: "Kalangala",
    text: "Kalangala district is located in southern central Uganda and is comprised of a series of islands situated on Lake Victoria. The estimated population in 2016 was 56,900 individuals, with the majority of residents located on Bugala Island, the largest island accounting for 63.2 per cent of total dry land in the district. Historically, the primary income-generating activities on the islands have consisted of fishing, tourism, and agriculture. Since the inception of the oil palm project in 2005, in the form of a private-public partnership between the government of Uganda and BIDCO Uganda Limited (operating as Oil Palm Uganda Limited, or OPUL), cultivation of oil palm has steadily become a key economic activity within the district",
    bigText: [
      "Kalangala district is located in southern central Uganda and is comprised of a series of islands situated on Lake Victoria. The estimated population in 2016 was 56,900 individuals, with the majority of residents located on Bugala Island, the largest island accounting for 63.2 per cent of total dry land in the district. Historically, the primary income-generating activities on the islands have consisted of fishing, tourism, and agriculture. Since the inception of the oil palm project in 2005, in the form of a private-public partnership between the government of Uganda and BIDCO Uganda Limited (operating as Oil Palm Uganda Limited, or OPUL), cultivation of oil palm has steadily become a key economic activity within the district. Under the umbrella of the VDOP, the promotion of oil palm production has been seen as a strategic effort to address high poverty rates and reduce Uganda’s dependency on oil imports 2 fishing. A 1% (108.7 acre) expansion in oil palm plantations raises total cash income in Kalangala by 242 million UGX and total real income by 210.1 million UGX. A 10% increase in oil palm productivity increases total cash income in Kalangala by nearly 5 billion UGX annually, with nearly half of the income gain going to non-oil-palm-producing households.",
      "Our simulations reveal that the entire Kalangala economy is now vulnerable to oil palm price shocks. Market linkages magnify the impacts of both positive and negative price shocks. Positive price shocks stimulate production, employment, and incomes throughout Kalangala. Negative shocks, on the other hand, have a disproportionately large negative impact on local incomes. Both positive and negative price shocks affect employment much more in non-palm-producing households than in palm farmer or palm worker households. This analysis underlines the importance of using an economy-wide approach to evaluate the impacts of development programs. The relative geographical isolation of Kalangala District helps shape the local economic impacts of oil palm. Barriers to trade, including reliance on ferries and long transportation times, effectively trap a good proportion of the economic spillover effects of palm development in Kalangala. Virtually all wages paid and most household purchases are within the local economy of Kalangala. This helps explain why the impacts on total Kalangala income far exceed the direct benefits of the project.",
      "Kalangala district is located in southern central Uganda and is comprised of a series of islands situated on Lake Victoria. The estimated population in 2016 was 56,900 individuals, with the vast majority of residents located on Bugala Island, the largest island accounting for 63.2 percent of total dry land in the district. Historically, the primary income-generating activities on the islands have consisted of fishing, tourism, and agriculture. Since the inception of the oil palm project in 2005, in the form of a private-public partnership between the government of Uganda and BIDCO Uganda Limited (operating as Oil Palm Uganda Limited, or OPUL), cultivation of oil palm has steadily become a key economic activity within the district. Under the umbrella of the VDOP, promotion of oil palm production has been seen as a strategic effort to address high poverty rates and reduce Uganda’s dependency on oil imports by increasing domestic production. At the time of the survey, roughly 10,000 hectares of palm oil had been planted, with 6,500 hectares operated by OPUL in the form of a nucleus estate. The remaining 3,500 hectares belong to 1,800 individual smallholders whom sell their fresh fruit bunches (FFBs) to one of two local mills operated by OPUL. As part of the project, the government of Uganda and IFAD established the KOPGT, which enables farmers to access credit; current loans total 13 million USD to smallholder growers.",
      "In addition to loans and extension services, KOPGT also acts as an intermediary between smallholders and OPUL by collecting FFBs from individual farmers and processing payments. It is evident that the livelihoods of local residents have been transformed as a result of the oil palm project. While the number of smallholder growers is relatively small, oil palm production and processing activities provide jobs for more than 3,000 workers, including employment with plantations, mills, and refining. Previous surveys indicate that the largest source of income on Bugala Island was the sale of palm oil, at 30% of total income (MOA, 2017). In addition, the project has drastically improved transportation and utility services on Bugala Island, developing over 250 kilometers of roads and providing continuous electricity to the majority of villages.",
    ],
  },
  {
    id: 5,
    img: icon1,
    title: "Mukono",
    text: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.",
    bigText: [
      "There are many variations of passages of Lorem Ipsum available, but the majority have suffered/n alteration in some form, by injected humour, or randomised words which don't look even slightly/n believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything/n embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat/n predefined chunks as necessary, making this the first true generator on the Internet. It uses a/n dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate/n Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition,/n injected humour, or non-characteristic words etc.",
    ],
  },
];
