import { useState } from "react";
import foot from "../assets/footer.png";
import {} from "react-icons";
import { BsTwitterX } from "react-icons/bs";
import { SlSocialLinkedin } from "react-icons/sl";
import { TfiWorld } from "react-icons/tfi";

const Footer = () => {
  const [formData, setFormData] = useState({
    name: "",
    email: "",
  });
  const [submitted, setSubmitted] = useState(false);
  const socialLinks = [
    {
      link: "https://x.com/NOPP_UG",
      icon: BsTwitterX,
    },
    {
      link: "",
      icon: "",
    },
    {
      link: "",
      icon: "",
    },
  ];

  const handleInputChange = (e) => {
    setFormData({
      ...formData,
      [e.target.name]: e.target.value,
    });
  };
  const handleSubmit = (e) => {
    e.preventDefault();
    setSubmitted(true);
    setFormData({
      name: "",
      email: "",
    });
  };

  return (
    <footer>
      <div className="footer">
        <div className="image">
          <img src={foot} alt="Footer logo" />
        </div>
        <div className="sect-one">
          <h2>MINISTRY VISION</h2>
          <p className="mission-p">
            A competitive, profitable and sustainable Agricultural Sector
          </p>
          <h2>MINISTRY MISSION</h2>
          <p className="mission-p">
            To transform subsistence farming to Commercial Agriculture
          </p>
          <h2>PROJECT GOAL</h2>
          <p className="mission-p">
            Inclusive rural transformation through Oil Palm Investment
          </p>
        </div>
        <div className="sect-two">
          <h2>PROJECT DEVELOPMENT OBJECTIVE</h2>
          <p className="mission-p">
            To sustainably increase rural incomes through opportunities
            generated by the establishment of an efficient Oil Palm Industry
            That complies with modern environmental and social standards
          </p>
          <h2>VALUES</h2>
          <p className="mission-p">
            Teamwork / Professionalism / Excellency / Commitment / Ownership /
            Integrity
          </p>
        </div>
        <div className="sect-three">
          <div id="contact">
            <h2>CONTACT US TODAY</h2>
            <p>
              1st Floor, JOCASA House, Plot 14, Nakasero road, +256(0)414230690,
              P.O Box 12041, Kampala Uganda.
            </p>
          </div>
          <form onSubmit={handleSubmit}>
            <label>
              <input
                type="text"
                name="name"
                placeholder="Enter your name"
                value={formData.name}
                onChange={handleInputChange}
              />
            </label>
            <label>
              <input
                type="email"
                name="email"
                placeholder="Enter your email"
                value={formData.email}
                onChange={handleInputChange}
              />
            </label>
            <button type="submit">Subscribe to Newsletter</button>
          </form>
          <div className="socials">
            <a href="https://x.com/NOPP_UG" target="_blank">
              <BsTwitterX />
            </a>
            <a
              href="https://www.linkedin.com/company/national-oil-palm-project/"
              target="_blank"
            >
              <SlSocialLinkedin />
            </a>
            <a href="https://www.agriculture.go.ug" target="_blank">
              <TfiWorld />
            </a>
          </div>
        </div>
      </div>
      <div className="foot"></div>
    </footer>
  );
};

export default Footer;
